config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index] do
    member do
      patch :set_admin
      patch :remove_admin
    end
  end
  
  resources :projects
  get 'home/index'
  
  get "up" => "rails/health#show", as: :rails_health_check

  # root "home#index"
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :friends
  def set_admin
    update(admin: true)
  end

  def remove_admin
    update(admin: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        @users = User.all if current_user&.admin?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all if current_user&.admin?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /projects or /projects.json
  def index
    @users = User.all if current_user&.admin?
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    # @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    # @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to projects_path, notice: "Not Authorized To Edit This Project" if @project.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :project_description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin, only: [:set_admin, :remove_admin, :index]
  
    def index
      @users = User.all if current_user&.admin?
    end
  
    def set_admin
      @user = User.find(params[:id])
      @user.set_admin
      redirect_to users_path, notice: 'User is now an admin.'
    end
  
    def remove_admin
      @user = User.find(params[:id])
      @user.remove_admin
      redirect_to users_path, notice: 'Admin rights removed.'
    end
  
    private
  
    def authorize_admin
      redirect_to root_path, alert: 'Access denied.' unless current_user.admin?
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to image_tag("logo.png", alt: "Image description", class: "img-class", height: 50, width: 50), root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
       <% link_to 'Projects', projects_path, class:"navbar-brand" %>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item btn btn-link">
       <i class="fa-solid fa-plus"></i>
       <%= link_to 'Add Project', new_project_path, class:"navbar-brand" %>
      </li>
      <li class="nav-item btn btn-link">
        <i class="fa-solid fa-gear"></i>
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"navbar-brand" %>
      </li>
      <li class="nav-item btn btn-link">
      <i class="fas fa-sign-out-alt"></i>
       <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class:"navbar-brand" %>
      </li>
      <% else %>
      <li class="nav-item btn btn-link">
        <%= link_to 'Sign Up', new_user_registration_path, class:"navbar-brand" %>
      </li>
      <li class="nav-item btn btn-link">
       <%= link_to 'Sign In', new_user_session_path, class:"navbar-brand" %>
      </li>
      <% end %>

    </ul>
   
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-bordered">
<thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Email</th>
    <th scope="col">Action</th>
  </tr>
</thead>
<tbody>
  <% @users.each do |user| %>
      <% if current_user != user %>
      <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.email %></td>
      <% unless user.admin? %>
          <td><%= link_to 'Make Admin', set_admin_user_path(user), data: { turbo_method: :patch } %></td> 
      <% else %>
          <td><%= link_to 'Remove Admin', remove_admin_user_path(user), data: { turbo_method: :patch } %></td>
      <% end %>
      </tr>
      <% end %>
  <% end %>
</tbody>
</table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>My Basecamp 1</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
    <%= render 'home/header' %>
    <% end %>
      
    <div class = "container">
    <br/>
  
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'View Users', home_index_path, class:"navbar-brand" %>
      <%= link_to 'View Projects', root_path, class:"navbar-brand" %>
    <% end %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% form.label :project_name, style: "display: block" %>
    <%= form.text_field :project_name, class:"form-control", placeholder:"Project Name" %>
  </div>

  <div class="form-group">
    <% form.label :project_description, style: "display: block" %>
    <%= form.text_area :project_description, class:"form-control", placeholder:"Project Description" %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, id: :project_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p  class="display-4">
    <%= project.project_name %>
  </p>

  <p class="lead">
    <%= project.project_description %><br>
    <% @project_user_id = project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "View", @project, class:"btn btn-secondary" %> 
  <%= link_to "Back", projects_path, class:"btn btn-dark" %>
</div>

app/views/projects/index.html.erb
<div class="container">
    <% if !user_signed_in? %>
    <div align = "center">
        <br/><br/><br/>
        <%= image_tag("logo.png", alt: "Image description", class: "img-class", height: 300, width: 300) %>
        <h1 class="font-weight-bold", style = "font-size: 5rem;">COLLABORATE</h1>
        <p>A project management tool for developers</p><br/>
        <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-secondary" %>&nbsp;&nbsp;
        <%= link_to 'Sign In', new_user_session_path, class:"btn btn-secondary" %>
    </div>
    <% else %>
        <h1 align = "center">Projects</h1><br/>
       <div class="row">
                
            <div class="col" id="projects">
                <div class="col p-3 mb-2 bg-light text-dark">
                    <i class="fas fa-folder-open"></i> All Projects
                </div>
                <% @projects.each do |project| %>
                    <div class="container mt-5">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                    <%= render project, class:"card-text" %>
                                    <p>
                                        <%= link_to "Show this project", project, class:"btn btn-primary" %>
                                    </p>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="col" id="projects">
                <div class="col p-3 mb-2 bg-light text-dark">
                    <i class="fas fa-user"></i>Created By Me
                </div>
                <% @projects.each do |project| %>
                    <% if project.user == current_user %>
                        <div class="container mt-5">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                        <%= render project, class:"card-text" %>
                                        <p>
                                            <%= link_to "Show this project", project, class:"btn btn-primary" %>
                                        </p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div class="col" id="projects">
                    <div class="col p-3 mb-2 bg-light text-dark">
                        <i class="fas fa-share-alt"></i>Shared With Me
                    </div>
            </div>
       </div><br/>
        <% link_to "New project", new_project_path, class:"btn btn-secondary" %>
    <% end %>
</div>

app/views/projects/new.html.erb
<h1>Add New Project</h1>
<br>
<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path, class:"btn btn-dark" %>
</div>

app/views/projects/show.html.erb
<div class="jumbotron" >
  <%= render @project %>
  <hr class="my-4">
  <div>
  <% if current_user.id == @project_user_id %>
  <i class="fa-solid fa-pen"></i>
  <%= link_to "Edit Project", edit_project_path(@project), class:"btn btn-secondary" %> 
  <% end %>
  <%= link_to "Back", projects_path, class:"btn btn-dark" %>
    
    <br><br>
    <% if current_user.id == @project_user_id %>
      <%= button_to "Destroy this project", @project, method: :delete, class:"btn btn-danger" %>
    <% end %>
  </div>
</div>